//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace com { namespace mtcmoscow { namespace SensorHub { namespace Humidity {

ref class HumidityConsumer;

public ref class HumidityJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property HumidityConsumer^ Consumer
    {
        HumidityConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ HumidityConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    HumidityConsumer^ m_consumer;
};

public ref class HumidityGetRHResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double RH
    {
        double get() { return m_value; }
    internal:
        void set(_In_ double value) { m_value = value; }
    }

    static HumidityGetRHResult^ CreateSuccessResult(_In_ double value)
    {
        auto result = ref new HumidityGetRHResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->RH = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static HumidityGetRHResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidityGetRHResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    double m_value;
};

public ref class HumiditySetRHResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static HumiditySetRHResult^ CreateSuccessResult()
    {
        auto result = ref new HumiditySetRHResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static HumiditySetRHResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumiditySetRHResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

} } } } 
