//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace com { namespace mtcmoscow { namespace SensorHub { namespace Temperature {

ref class TemperatureConsumer;

public ref class TemperatureJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property TemperatureConsumer^ Consumer
    {
        TemperatureConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ TemperatureConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    TemperatureConsumer^ m_consumer;
};

public ref class TemperatureGetCelsiusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double Celsius
    {
        double get() { return m_value; }
    internal:
        void set(_In_ double value) { m_value = value; }
    }

    static TemperatureGetCelsiusResult^ CreateSuccessResult(_In_ double value)
    {
        auto result = ref new TemperatureGetCelsiusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Celsius = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TemperatureGetCelsiusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TemperatureGetCelsiusResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    double m_value;
};

public ref class TemperatureSetCelsiusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static TemperatureSetCelsiusResult^ CreateSuccessResult()
    {
        auto result = ref new TemperatureSetCelsiusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TemperatureSetCelsiusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TemperatureSetCelsiusResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class TemperatureGetFahrenheitsResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double Fahrenheits
    {
        double get() { return m_value; }
    internal:
        void set(_In_ double value) { m_value = value; }
    }

    static TemperatureGetFahrenheitsResult^ CreateSuccessResult(_In_ double value)
    {
        auto result = ref new TemperatureGetFahrenheitsResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Fahrenheits = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TemperatureGetFahrenheitsResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TemperatureGetFahrenheitsResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    double m_value;
};

public ref class TemperatureSetFahrenheitsResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static TemperatureSetFahrenheitsResult^ CreateSuccessResult()
    {
        auto result = ref new TemperatureSetFahrenheitsResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static TemperatureSetFahrenheitsResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new TemperatureSetFahrenheitsResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

} } } } 
