//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace com { namespace mtcmoscow { namespace SensorHub { namespace Pressure {

ref class PressureConsumer;

public ref class PressureJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property PressureConsumer^ Consumer
    {
        PressureConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ PressureConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    PressureConsumer^ m_consumer;
};

public ref class PressureGetAltitudeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double Altitude
    {
        double get() { return m_value; }
    internal:
        void set(_In_ double value) { m_value = value; }
    }

    static PressureGetAltitudeResult^ CreateSuccessResult(_In_ double value)
    {
        auto result = ref new PressureGetAltitudeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Altitude = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PressureGetAltitudeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PressureGetAltitudeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    double m_value;
};

public ref class PressureSetAltitudeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static PressureSetAltitudeResult^ CreateSuccessResult()
    {
        auto result = ref new PressureSetAltitudeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PressureSetAltitudeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PressureSetAltitudeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class PressureGetInchesOfMercuryResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double InchesOfMercury
    {
        double get() { return m_value; }
    internal:
        void set(_In_ double value) { m_value = value; }
    }

    static PressureGetInchesOfMercuryResult^ CreateSuccessResult(_In_ double value)
    {
        auto result = ref new PressureGetInchesOfMercuryResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->InchesOfMercury = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PressureGetInchesOfMercuryResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PressureGetInchesOfMercuryResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    double m_value;
};

public ref class PressureSetInchesOfMercuryResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static PressureSetInchesOfMercuryResult^ CreateSuccessResult()
    {
        auto result = ref new PressureSetInchesOfMercuryResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PressureSetInchesOfMercuryResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PressureSetInchesOfMercuryResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class PressureGetMmOfMercuryResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double MmOfMercury
    {
        double get() { return m_value; }
    internal:
        void set(_In_ double value) { m_value = value; }
    }

    static PressureGetMmOfMercuryResult^ CreateSuccessResult(_In_ double value)
    {
        auto result = ref new PressureGetMmOfMercuryResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->MmOfMercury = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PressureGetMmOfMercuryResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PressureGetMmOfMercuryResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    double m_value;
};

public ref class PressureSetMmOfMercuryResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static PressureSetMmOfMercuryResult^ CreateSuccessResult()
    {
        auto result = ref new PressureSetMmOfMercuryResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PressureSetMmOfMercuryResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PressureSetMmOfMercuryResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class PressureGetPascalResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property double Pascal
    {
        double get() { return m_value; }
    internal:
        void set(_In_ double value) { m_value = value; }
    }

    static PressureGetPascalResult^ CreateSuccessResult(_In_ double value)
    {
        auto result = ref new PressureGetPascalResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Pascal = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PressureGetPascalResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PressureGetPascalResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    double m_value;
};

public ref class PressureSetPascalResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static PressureSetPascalResult^ CreateSuccessResult()
    {
        auto result = ref new PressureSetPascalResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PressureSetPascalResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PressureSetPascalResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

} } } } 
